add_newline = false
format = """
[░▒▓](#555556)\
[ 󰣇 ](bg:#555556 fg:#ffffff)\
[](bg:#614041 fg:#555556)\
$directory\
[](fg:#614041 bg:#6D2B2C)\
$git_branch\
$git_status\
[](fg:#6D2B2C bg:#791616)\
[](fg:#791616 bg:#850101)\
[ ](fg:#850101)\
"""

[directory]
style = "fg:#e3e5e5 bg:#614041"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#6D2B2C"
format = '[[ $symbol $branch ](fg:#ffffff bg:#6D2B2C)]($style)'

[git_status]
style = "bg:#6D2B2C"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#6D2B2C)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#e9acff"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

